language: python
python:
  - 3.3
  - 3.4
branches:
  only:
    - master
    - develop
notifications:
  email: false

sudo: false

jdk:
  - oraclejdk7

before_install:
  # install Neo4j locally:
  - wget dist.neo4j.org/neo4j-community-2.2.0-unix.tar.gz
  - tar -xzf neo4j-community-2.2.0-unix.tar.gz
  - sed -i.bak s/dbms.security.auth_enabled=true/dbms.security.auth_enabled=false/g neo4j-community-2.2.0/conf/neo4j-server.properties
  - neo4j-community-2.2.0/bin/neo4j start
  - bash continuous-integration/travis/install.sh

# Install packages
install:
  - python setup.py install

# Run test
script:
  - "coverage run --source=annograph setup.py test"

# Calculate coverage
after_success:
  - coveralls
