language: python
python:
  - 3.4
  - 3.5
branches:
  only:
    - master
    - develop
notifications:
  email: false

sudo: false

jdk:
  - oraclejdk7

before_install:
  # install Neo4j locally:
  - wget dist.neo4j.org/neo4j-community-2.2.5-unix.tar.gz
  - tar -xzf neo4j-community-2.2.5-unix.tar.gz
  - sed -i.bak s/dbms.security.auth_enabled=true/dbms.security.auth_enabled=false/g neo4j-community-2.2.5/conf/neo4j-server.properties
  - neo4j-community-2.2.5/bin/neo4j start
  - bash continuous-integration/travis/install.sh

# Install packages
install:
  - export PATH="$HOME/miniconda/miniconda/bin:$PATH"
  - source activate test-environment
  - which python
  - conda list
  - python setup.py install

# Run test
script:
  - "coverage run --source=polyglotdb setup.py test"

# Calculate coverage
after_success:
  - coveralls

cache:
  pip: true
  directories:
    - $HOME/miniconda
